/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryCommercialPhotographyRouteImport } from './routes/gallery/commercial-photography'
import { Route as GalleryAdditionalDesignStudiesRouteImport } from './routes/gallery/additional-design-studies'
import { Route as CaseStudyTraditionalMedicinalsRouteImport } from './routes/case-study/traditional-medicinals'
import { Route as CaseStudyTogethxrRouteImport } from './routes/case-study/togethxr'
import { Route as CaseStudyNalgeneRouteImport } from './routes/case-study/nalgene'
import { Route as CaseStudyDeborahPaganiRouteImport } from './routes/case-study/deborah-pagani'

const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryCommercialPhotographyRoute =
  GalleryCommercialPhotographyRouteImport.update({
    id: '/gallery/commercial-photography',
    path: '/gallery/commercial-photography',
    getParentRoute: () => rootRouteImport,
  } as any)
const GalleryAdditionalDesignStudiesRoute =
  GalleryAdditionalDesignStudiesRouteImport.update({
    id: '/gallery/additional-design-studies',
    path: '/gallery/additional-design-studies',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudyTraditionalMedicinalsRoute =
  CaseStudyTraditionalMedicinalsRouteImport.update({
    id: '/case-study/traditional-medicinals',
    path: '/case-study/traditional-medicinals',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudyTogethxrRoute = CaseStudyTogethxrRouteImport.update({
  id: '/case-study/togethxr',
  path: '/case-study/togethxr',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudyNalgeneRoute = CaseStudyNalgeneRouteImport.update({
  id: '/case-study/nalgene',
  path: '/case-study/nalgene',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudyDeborahPaganiRoute = CaseStudyDeborahPaganiRouteImport.update({
  id: '/case-study/deborah-pagani',
  path: '/case-study/deborah-pagani',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap': typeof SitemapRoute
  '/case-study/deborah-pagani': typeof CaseStudyDeborahPaganiRoute
  '/case-study/nalgene': typeof CaseStudyNalgeneRoute
  '/case-study/togethxr': typeof CaseStudyTogethxrRoute
  '/case-study/traditional-medicinals': typeof CaseStudyTraditionalMedicinalsRoute
  '/gallery/additional-design-studies': typeof GalleryAdditionalDesignStudiesRoute
  '/gallery/commercial-photography': typeof GalleryCommercialPhotographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap': typeof SitemapRoute
  '/case-study/deborah-pagani': typeof CaseStudyDeborahPaganiRoute
  '/case-study/nalgene': typeof CaseStudyNalgeneRoute
  '/case-study/togethxr': typeof CaseStudyTogethxrRoute
  '/case-study/traditional-medicinals': typeof CaseStudyTraditionalMedicinalsRoute
  '/gallery/additional-design-studies': typeof GalleryAdditionalDesignStudiesRoute
  '/gallery/commercial-photography': typeof GalleryCommercialPhotographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap': typeof SitemapRoute
  '/case-study/deborah-pagani': typeof CaseStudyDeborahPaganiRoute
  '/case-study/nalgene': typeof CaseStudyNalgeneRoute
  '/case-study/togethxr': typeof CaseStudyTogethxrRoute
  '/case-study/traditional-medicinals': typeof CaseStudyTraditionalMedicinalsRoute
  '/gallery/additional-design-studies': typeof GalleryAdditionalDesignStudiesRoute
  '/gallery/commercial-photography': typeof GalleryCommercialPhotographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap'
    | '/case-study/deborah-pagani'
    | '/case-study/nalgene'
    | '/case-study/togethxr'
    | '/case-study/traditional-medicinals'
    | '/gallery/additional-design-studies'
    | '/gallery/commercial-photography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap'
    | '/case-study/deborah-pagani'
    | '/case-study/nalgene'
    | '/case-study/togethxr'
    | '/case-study/traditional-medicinals'
    | '/gallery/additional-design-studies'
    | '/gallery/commercial-photography'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap'
    | '/case-study/deborah-pagani'
    | '/case-study/nalgene'
    | '/case-study/togethxr'
    | '/case-study/traditional-medicinals'
    | '/gallery/additional-design-studies'
    | '/gallery/commercial-photography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapRoute: typeof SitemapRoute
  CaseStudyDeborahPaganiRoute: typeof CaseStudyDeborahPaganiRoute
  CaseStudyNalgeneRoute: typeof CaseStudyNalgeneRoute
  CaseStudyTogethxrRoute: typeof CaseStudyTogethxrRoute
  CaseStudyTraditionalMedicinalsRoute: typeof CaseStudyTraditionalMedicinalsRoute
  GalleryAdditionalDesignStudiesRoute: typeof GalleryAdditionalDesignStudiesRoute
  GalleryCommercialPhotographyRoute: typeof GalleryCommercialPhotographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/commercial-photography': {
      id: '/gallery/commercial-photography'
      path: '/gallery/commercial-photography'
      fullPath: '/gallery/commercial-photography'
      preLoaderRoute: typeof GalleryCommercialPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/additional-design-studies': {
      id: '/gallery/additional-design-studies'
      path: '/gallery/additional-design-studies'
      fullPath: '/gallery/additional-design-studies'
      preLoaderRoute: typeof GalleryAdditionalDesignStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study/traditional-medicinals': {
      id: '/case-study/traditional-medicinals'
      path: '/case-study/traditional-medicinals'
      fullPath: '/case-study/traditional-medicinals'
      preLoaderRoute: typeof CaseStudyTraditionalMedicinalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study/togethxr': {
      id: '/case-study/togethxr'
      path: '/case-study/togethxr'
      fullPath: '/case-study/togethxr'
      preLoaderRoute: typeof CaseStudyTogethxrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study/nalgene': {
      id: '/case-study/nalgene'
      path: '/case-study/nalgene'
      fullPath: '/case-study/nalgene'
      preLoaderRoute: typeof CaseStudyNalgeneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study/deborah-pagani': {
      id: '/case-study/deborah-pagani'
      path: '/case-study/deborah-pagani'
      fullPath: '/case-study/deborah-pagani'
      preLoaderRoute: typeof CaseStudyDeborahPaganiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapRoute: SitemapRoute,
  CaseStudyDeborahPaganiRoute: CaseStudyDeborahPaganiRoute,
  CaseStudyNalgeneRoute: CaseStudyNalgeneRoute,
  CaseStudyTogethxrRoute: CaseStudyTogethxrRoute,
  CaseStudyTraditionalMedicinalsRoute: CaseStudyTraditionalMedicinalsRoute,
  GalleryAdditionalDesignStudiesRoute: GalleryAdditionalDesignStudiesRoute,
  GalleryCommercialPhotographyRoute: GalleryCommercialPhotographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
